### ISSUE TITLE
What is python-autobahn?

### ISSUE THREAD

**Issue by up2smoke** [bastianraschke/vibelightgateway#1]
![IMG_20210128_101535](https://user-images.githubusercontent.com/35378113/106116193-ea88a100-6151-11eb-9aea-7d0330dfc724.jpg)

I'm trying on a Raspberry Pi Zero w

**Comment by bastianraschke** [comment]
The software is designed for old Debian 7, I guess the Python 2 package does not exists anymore, https://github.com/bastianraschke/vibelightgateway/blob/master/src/debian/control#L17 need to change to `python3-autobahn` but there maybe some problems when using Python 3. Nothing complex but I have no motivation to do this because I don't use the software anymore.
